#!/bin/bash
# Search for unique Deny message and report new messages.
mkdir -p /var/tmp/learner/ 2> /dev/null
if [ -f /var/tmp/learner/lock-deny-sorter ]; then
        exit 1
else
        touch /var/tmp/learner/lock-deny-sorter
        touch /var/tmp/learner/deny.log /var/tmp/learner/deny.last /var/tmp/learner/deny.dat
        cp /var/tmp/learner/deny.log /var/tmp/learner/deny.last
        cat /var/tmp/learner/deny.last /var/tmp/learner/deny.dat /var/tmp/learner/new.deny > /var/tmp/learner/deny.archive
        awk '!x[$0]++' /var/tmp/learner/deny.archive > /var/tmp/learner/deny.dat
        grep Deny /var/log/net.log  > /var/tmp/learner/deny.log
        awk '!x[$0]++' /var/tmp/learner/deny.log > /var/tmp/learner/deny.tmp
        cp /var/tmp/learner/deny.tmp /var/tmp/learner/deny.log
        cp /dev/null /var/tmp/learner/holding
        cp /var/tmp/learner/deny.last /var/tmp/learner/deny.in
                cat /var/tmp/learner/deny.archive |  while read line; do
                lock=$(echo "$line" | tr -cd '[[:alnum:]]._-' );
                touch /var/tmp/learner/"$lock".lock ;
                echo "$line" > /var/tmp/learner/"$lock".lock ;
        done
        cat /var/tmp/learner/*lock | sort -u > /var/tmp/learner/lock.dat
        join -v 1 <(sort /var/log/net.log) <(sort /var/tmp/learner/lock.dat) | sort -u > /var/tmp/learner/new.deny
        cat /var/tmp/learner/new.deny >> /var/log/new-deny.log
        rm /var/tmp/learner/lock-deny-sorter
fi
